---
title: "Genomic loci to compartment distance ImageJ plugin"
author: "Omid Gholamalamdari"
date: "5/24/2019"
output: rmarkdown::github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(ggplot2)
```

# Disclaimer
This work is in progress and unpublished. Feel free to use it at your own risk.

For a brief description of the method see: [Intro_to_module.pdf](https://github.com/omidalam/compartment_dist/blob/master/Intro_to_module.pdf)

# Goal
We are often interested in finding the relative distance of genomic loci with respect to a nuclear compartment (e.g. Nuclear Speckles, Nucleoulus) in our microscopic experiments. The idea behind this module is formed based on conversations between Dr. Andrew Belmont's lab members. Please acknowledge/cite (Our future paper). 

# Installation
- Make sure you have an up-to-date version of FIJI/ImageJ.
- For Windows: copy the "Loci_Compartment_Distance.py" in "C:\Program Files\ImageJ\plugins"
- For mac: right-click on FIJI in your application folder -> Show package contents -> copy the "Loci_Compartment_Distance.py" in the plugins folder.
- Once FIJI restarted, you can find it under the plugins menu.





